### ISSUE TITLE
Description under title

### ISSUE THREAD

**Issue by lfarah** [simformsolutions/SSCustomTabMenu#1]
Please add a description under the title, to inform your users what the lib is about

<img width="599" alt="screen shot 2018-01-16 at 2 47 41 pm" src="https://user-images.githubusercontent.com/6511079/35000706-3cb51f8e-facc-11e7-8abc-b00c8be58065.png">

Once this is closed, we can approve your [PR in AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/2220)

**Comment by simform-solutions** [comment]
Description added
